spring:
  main:
    log-startup-info: false
    banner-mode: off
  sql:
    init:
      mode: always

  # в jdbc-url укажите, что данные нужно сохранять в файл
  datasource:
    url: "jdbc:h2:file:./db/filmorate"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "password"

filmorate:
  film:
    popular:
      show:
        count: 10
